[build]
release = true
public_url = "/hodei-draw/"

[tools]
# Usa wasm-bindgen por defecto

# Hook para compilar Tailwind CSS automáticamente
[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwindcss", "-i", "input.css", "-o", "styles.css"]
