[package]
name = "momentum-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "momentum_core"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
